package com.iudigital.funcionariocrud.presentacion;

import com.iudigital.funcionariocrud.Controller.FuncionarioController;
import com.iudigital.funcionariocrud.domain.Funcionario;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Main extends javax.swing.JFrame {

    private final FuncionarioController funcionarioController;
    private static final String[] COLUMNS = {"Id", "#Documento", "Nombres", "Apellidos",
        "Estado_civil", "Sexo", "Direccion", "Telefono", "Fecha_nac"};
    private static final String SELECCIONE = "SELECCIONE";

    public Main() {
        initComponents();
        txtNombres_edit.setEditable(false);
        funcionarioController = new FuncionarioController();
        listFuncionarios();
        addListener();
    }

    private void listFuncionarios() {
        cbxFuncionario_id.removeAllItems();
        Funcionario funcionario1 = new Funcionario();
        funcionario1.setNombres(SELECCIONE);
        funcionario1.setApellidos("");
        cbxFuncionario_id.addItem(funcionario1);

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }

        tblFuncionarios.setModel(defaultTableModel);

        try {

            List<Funcionario> funcionarios = funcionarioController.getFuncionarios();
            if (funcionarios.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(funcionarios.size());
            int row = 0;
            for (Funcionario funcionario : funcionarios) {
                defaultTableModel.setValueAt(funcionario.getIdFuncionario(), row, 0);
                defaultTableModel.setValueAt(funcionario.getNumeroIdentificacion(), row, 1);
                defaultTableModel.setValueAt(funcionario.getNombres(), row, 2);
                defaultTableModel.setValueAt(funcionario.getApellidos(), row, 3);
                defaultTableModel.setValueAt(funcionario.getEstadoCivil(), row, 4);
                defaultTableModel.setValueAt(funcionario.getSexo(), row, 5);
                defaultTableModel.setValueAt(funcionario.getDireccion(), row, 6);
                defaultTableModel.setValueAt(funcionario.getTelefono(), row, 7);
                defaultTableModel.setValueAt(funcionario.getFechaNacimiento(), row, 8);
                row++;

                cbxFuncionario_id.addItem(funcionario);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void addListener() {
        cbxFuncionario_id.addItemListener((ItemEvent event) -> {
        Funcionario selectedFuncionario = (Funcionario) event.getItem();
        if (selectedFuncionario.getNombres().equals(SELECCIONE)) {
            txtApellidos_edit.setText("");
            txtEstado_civil_edit.setText("");
            txtSexo_edit.setText("");
            txtDireccion_edit.setText("");
            txtTelefono_edit.setText("");
            txtFecha_nac_edit.setText("");
        } else {
            txtNombres_edit.setText(String.valueOf(selectedFuncionario.getNombres()));
            txtNumero_Doc_edit.setText(selectedFuncionario.getNumeroIdentificacion());
            txtNombres_edit.setText(selectedFuncionario.getNombres());
            txtApellidos_edit.setText(selectedFuncionario.getApellidos());
            txtEstado_civil_edit.setText(selectedFuncionario.getEstadoCivil());
            txtSexo_edit.setText(selectedFuncionario.getSexo());
            txtDireccion_edit.setText(selectedFuncionario.getDireccion());
            txtTelefono_edit.setText(selectedFuncionario.getTelefono());
            txtFecha_nac_edit.setText(String.valueOf(selectedFuncionario.getFechaNacimiento()));

            
         }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblEstado_civil = new javax.swing.JLabel();
        txtEstado_civil = new javax.swing.JTextField();
        lblNumero_Doc = new javax.swing.JLabel();
        txtNumero_Doc = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblFecha_Nac = new javax.swing.JLabel();
        txtFecha_Nac = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        tblFuncionariostbl = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblFuncionario_id = new javax.swing.JPanel();
        lblFuncionarios = new javax.swing.JLabel();
        lblNumero_doc_edit = new javax.swing.JLabel();
        txtNumero_Doc_edit = new javax.swing.JTextField();
        lblNombres_edit = new javax.swing.JLabel();
        txtNombres_edit = new javax.swing.JTextField();
        lblApellidos_edit = new javax.swing.JLabel();
        txtApellidos_edit = new javax.swing.JTextField();
        lblEstado_civil_edit = new javax.swing.JLabel();
        txtEstado_civil_edit = new javax.swing.JTextField();
        lblSexo_edit = new javax.swing.JLabel();
        txtSexo_edit = new javax.swing.JTextField();
        lblDireccion_edit = new javax.swing.JLabel();
        txtDireccion_edit = new javax.swing.JTextField();
        lblTelefono_edit = new javax.swing.JLabel();
        txtTelefono_edit = new javax.swing.JTextField();
        lblFecha_nac_edit = new javax.swing.JLabel();
        txtFecha_nac_edit = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbxFuncionario_id = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Ingrese datos del funcionario"));

        lblNombre.setText("      Nombres");

        lblApellidos.setText("      Apellidos");

        lblEstado_civil.setText(" Estado_civil");

        lblNumero_Doc.setText("Numero_documento");

        lblSexo.setText("   Sexo");

        lblDireccion.setText("    Direccion");

        lblTelefono.setText("   Telefono");

        lblFecha_Nac.setText("Fecha_Nacimiento");

        btnCreate.setText("GUARDAR");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumero_Doc)
                                    .addComponent(txtNumero_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEstado_civil, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(txtEstado_civil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha_Nac, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFecha_Nac))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(btnCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero_Doc)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado_civil)
                    .addComponent(lblSexo)
                    .addComponent(lblDireccion)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha_Nac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha_Nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                .addComponent(btnCreate))
        );

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblFuncionariostbl.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblFuncionariostbl))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblFuncionariostbl, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel.addTab("Crear - Listar Funcionarios", jPanel1);

        lblFuncionario_id.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes campos"));

        lblFuncionarios.setText("Funcionarios");

        lblNumero_doc_edit.setText("  Numero_documento");

        lblNombres_edit.setText("  Nombres");

        lblApellidos_edit.setText("  Apellidos");

        lblEstado_civil_edit.setText("Estado Civil");

        lblSexo_edit.setText("Sexo");

        lblDireccion_edit.setText("  Direccion");

        lblTelefono_edit.setText("  Telefono");

        lblFecha_nac_edit.setText("Fecha_nacimiento");

        txtFecha_nac_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha_nac_editActionPerformed(evt);
            }
        });

        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("ElLIMINAR");

        cbxFuncionario_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncionario_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblFuncionario_idLayout = new javax.swing.GroupLayout(lblFuncionario_id);
        lblFuncionario_id.setLayout(lblFuncionario_idLayout);
        lblFuncionario_idLayout.setHorizontalGroup(
            lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblFuncionario_idLayout.createSequentialGroup()
                .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblFuncionario_idLayout.createSequentialGroup()
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstado_civil_edit)
                            .addComponent(lblEstado_civil_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSexo_edit)
                            .addComponent(lblSexo_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccion_edit)
                            .addComponent(lblDireccion_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTelefono_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtTelefono_edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha_nac_edit)
                            .addComponent(lblFecha_nac_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(lblFuncionario_idLayout.createSequentialGroup()
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumero_Doc_edit)
                            .addComponent(lblNumero_doc_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombres_edit)
                            .addComponent(lblNombres_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidos_edit)
                            .addComponent(lblApellidos_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(lblFuncionario_idLayout.createSequentialGroup()
                        .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblFuncionario_idLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxFuncionario_id, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(lblFuncionario_idLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        lblFuncionario_idLayout.setVerticalGroup(
            lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblFuncionario_idLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFuncionario_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero_doc_edit)
                    .addComponent(lblNombres_edit)
                    .addComponent(lblApellidos_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero_Doc_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado_civil_edit)
                    .addComponent(lblSexo_edit)
                    .addComponent(lblDireccion_edit)
                    .addComponent(lblTelefono_edit)
                    .addComponent(lblFecha_nac_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado_civil_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha_nac_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(lblFuncionario_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFuncionario_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuncionario_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel.addTab("Actualizar - Eliminar Funcionarios", jPanel2);

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 670, 430));

        jLabel1.setText("ADMINISTRADOR DE FUNCIONARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 200, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFecha_nac_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha_nac_editActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha_nac_editActionPerformed

    private void cbxFuncionario_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncionario_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFuncionario_idActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        if(txtNumero_Doc.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite numero de documento");
            txtNumero_Doc.requestFocus();
            return;
        }
        
        if(txtNombres.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite nombres");
            txtNombres.requestFocus();
            return;
        }
        
        if(txtApellidos.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite apellidos");
            txtApellidos.requestFocus();
            return;
        }
        
        if(txtEstado_civil.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite estado civil");
            txtEstado_civil.requestFocus();
            return;
        }
        
        if(txtSexo.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Sexo");
            txtSexo.requestFocus();
            return;
        }
        
        if(txtDireccion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite direccion");
            txtDireccion.requestFocus();
            return;
        }
        
        if(txtTelefono.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Telefono");
            txtTelefono.requestFocus();
            return;
        }
        
        if(txtFecha_Nac.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Fecha de nacimiento");
            txtFecha_Nac.requestFocus();
            return;
        }
        
        Funcionario funcionario = new Funcionario();
        funcionario.setNumeroIdentificacion(txtNumero_Doc.getText().trim());
        funcionario.setNombres(txtNombres.getText().trim());
        funcionario.setApellidos(txtApellidos.getText().trim());
        funcionario.setEstadoCivil(txtEstado_civil.getText().trim());
        funcionario.setSexo(txtSexo.getText().trim());
        funcionario.setDireccion(txtDireccion.getText().trim());
        funcionario.setTelefono(txtTelefono.getText().trim());
        funcionario.setFechaNacimiento(LocalDate.MIN);
        try {
            funcionarioController.createOneFuncionario(funcionario);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNumero_Doc.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEstado_civil.setText("");
        txtSexo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtFecha_Nac.setText("");
        listFuncionarios();
        JOptionPane.showMessageDialog(null, "Funcinanrio creado con éxito");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Funcionario> cbxFuncionario_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidos_edit;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccion_edit;
    private javax.swing.JLabel lblEstado_civil;
    private javax.swing.JLabel lblEstado_civil_edit;
    private javax.swing.JLabel lblFecha_Nac;
    private javax.swing.JLabel lblFecha_nac_edit;
    private javax.swing.JPanel lblFuncionario_id;
    private javax.swing.JLabel lblFuncionarios;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombres_edit;
    private javax.swing.JLabel lblNumero_Doc;
    private javax.swing.JLabel lblNumero_doc_edit;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSexo_edit;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono_edit;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JScrollPane tblFuncionariostbl;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidos_edit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion_edit;
    private javax.swing.JTextField txtEstado_civil;
    private javax.swing.JTextField txtEstado_civil_edit;
    private javax.swing.JTextField txtFecha_Nac;
    private javax.swing.JTextField txtFecha_nac_edit;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNombres_edit;
    private javax.swing.JTextField txtNumero_Doc;
    private javax.swing.JTextField txtNumero_Doc_edit;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSexo_edit;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono_edit;
    // End of variables declaration//GEN-END:variables
}
